version: "3"

services:
  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - 8080:80
    networks:
      - app-network
    volumes:
      - ./app:/var/www/html/
      - ./default.conf:/etc/nginx/conf.d/default.conf
  php:
    container_name: php
    build:
      context: .
    volumes:
      - ./app/:/var/www/html/
    networks:
      - app-network
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: discover_client_host=0 client_host=host.docker.internal client_port=9003 start_with_request=yes

networks:
  app-network:
    driver: bridge